steps:
# Build the container image
-   name: 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo'
    args: ['build', '-t', 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo', '.']
# Push the image to Container Registry
-   name: 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo'
    args: ['push', 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo']
# Deploy image to Cloud Run
-   name: 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo'
    args: ['run', 'deploy', 'conversational-ai-demo-2', '--image', 'asia.gcr.io/kalschi-demo-001/conversational-ai-demo', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
-   asia.gcr.io/kalschi-demo-001/conversational-ai-demo