apiVersion: apps/v1
kind: Deployment
metadata:
    name: dialogflow-fulfillment
spec:
    selector:
        matchLabels:
            app: dialogflow-fulfillment
    replicas: 1
    template:
        metadata:
            labels:
                app: dialogflow-fulfillment
        spec:
            containers:
            -   name: dialogflow-fulfillment
                image: gcr.io/kalschi-agones/conversational-ai-demo:0.01
                imagePullPolicy: Always
                ports:
                    -   name: http
                        containerPort: 8080
                env:
                    -   name: PROJECT_ID
                        value: kalschi-agones
                    -   name: LOCATION
                        value: global
                    -   name: NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                    -   name: CONTAINER
                        value: "dialogflow-fulfillment"